Allow doctrine/dbal 3.1
sonata-project/SonataDoctrineORMAdminBundle pull request #1549
Opened 2021-10-15 13:16 UTC by simonberger

## Subject
This allows doctrine/dbal 3.1. breaking changes do not affect us.

## Todos

- [ ]  A Release with https://github.com/sonata-project/EntityAuditBundle/pull/444

## Changelog
```markdown
### Added
- Added support for Doctrine DBAL 3.1.
```

## Closes

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1548

2021-10-15 14:06 UTC, core23 submitted a review, later dismissed

2021-10-15 14:13 UTC, VincentLanglet requested changes
Test are running on dbal 2

2021-10-15 14:14 UTC, simonberger commented
Yes, we need to re-run once the new EntitiyAuditBundle release is there and should also be merge just then.

2021-10-15 14:20 UTC, VincentLanglet commented
> Yes, we need to re-run once the new EntitiyAuditBundle release is there and should also be merge just then.

Not sure about this, since unit tests and phpstan is already failing.
Another PR to just fix tests could be helpful

2021-10-15 14:29 UTC, simonberger commented
Ah ok didn't look at the check output at all. Most is related to new ORM versions but also sonata-project/twig-extensions.

I could have a look at that next week. More than welcome if someone else finds the time.

2021-10-15 15:03 UTC, simonberger commented
Reverted increasing the minimum ORM version (for now) to see if tests run through then. The missing table errors are looking strange.
It seems I need to be allowed to run the pipelines for every commit tho.

2021-10-17 17:33 UTC, simonberger commented
I fixed the PHPStan problems from a previous run. In my setup most likely the relevant tests causing the issue when increasing the ORM version are skipped which means it is impossible for me to reproduce and fix the possible problem with the schema preparation in the database (or it was just temporary).
Having to wait to see the pipelines in the PR does not make it easier. 😉

2021-10-17 18:11 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-10-26 14:01 UTC, closed without merging